apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hemlapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AliAkbar986/helmargo.git
    targetRevision: HEAD
    path: templates
  destination: 
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
